// i18n translations for MirrorSpeed landing
// Languages: zh, en, fr, es, de, it, ja, ko, tr, ar, ru

export const SUPPORTED_LANGS = [
  { code: "en", label: "English", native: "English" },
  { code: "zh", label: "Chinese", native: "中文" },
  { code: "fr", label: "French", native: "Français" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "it", label: "Italian", native: "Italiano" },
  { code: "ja", label: "Japanese", native: "日本語" },
  { code: "ko", label: "Korean", native: "한국어" },
  { code: "tr", label: "Turkish", native: "Türkçe" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "ru", label: "Russian", native: "Русский" },
];

export const RTL_LANGS = ["ar"];

// Country code -> language (rough geo guess from timezone)
export const TZ_TO_LANG = {
  "Asia/Shanghai": "zh", "Asia/Hong_Kong": "zh", "Asia/Taipei": "zh",
  "Asia/Tokyo": "ja",
  "Asia/Seoul": "ko",
  "Europe/Paris": "fr", "Africa/Casablanca": "fr",
  "Europe/Madrid": "es", "America/Mexico_City": "es", "America/Argentina/Buenos_Aires": "es",
  "Europe/Berlin": "de", "Europe/Vienna": "de", "Europe/Zurich": "de",
  "Europe/Rome": "it",
  "Europe/Istanbul": "tr",
  "Asia/Dubai": "ar", "Asia/Riyadh": "ar", "Africa/Cairo": "ar",
  "Europe/Moscow": "ru", "Asia/Yekaterinburg": "ru",
};

const D = {
  // Nav
  nav_features: { en: "Features", zh: "功能", fr: "Fonctionnalités", es: "Funciones", de: "Funktionen", it: "Funzioni", ja: "機能", ko: "기능", tr: "Özellikler", ar: "الميزات", ru: "Возможности" },
  nav_network: { en: "Network", zh: "节点网络", fr: "Réseau", es: "Red", de: "Netzwerk", it: "Rete", ja: "ネットワーク", ko: "네트워크", tr: "Ağ", ar: "الشبكة", ru: "Сеть" },
  nav_pricing: { en: "Pricing", zh: "价格", fr: "Tarifs", es: "Precios", de: "Preise", it: "Prezzi", ja: "料金", ko: "요금", tr: "Fiyatlar", ar: "الأسعار", ru: "Цены" },
  nav_faq: { en: "FAQ", zh: "常见问题", fr: "FAQ", es: "FAQ", de: "FAQ", it: "FAQ", ja: "よくある質問", ko: "자주 묻는 질문", tr: "SSS", ar: "الأسئلة", ru: "Вопросы" },
  nav_blog: { en: "Blog", zh: "博客", fr: "Blog", es: "Blog", de: "Blog", it: "Blog", ja: "ブログ", ko: "블로그", tr: "Blog", ar: "المدونة", ru: "Блог" },
  nav_signin: { en: "Sign in", zh: "登录", fr: "Connexion", es: "Iniciar sesión", de: "Anmelden", it: "Accedi", ja: "ログイン", ko: "로그인", tr: "Giriş yap", ar: "تسجيل الدخول", ru: "Войти" },
  nav_get_started: { en: "Get Started", zh: "立即开始", fr: "Commencer", es: "Comenzar", de: "Loslegen", it: "Inizia", ja: "始める", ko: "시작하기", tr: "Başla", ar: "ابدأ الآن", ru: "Начать" },

  // Hero
  hero_badge: { en: "Engine v3.2 · Edge Network Online", zh: "引擎 v3.2 · 边缘网络在线", fr: "Moteur v3.2 · Réseau Edge en ligne", es: "Motor v3.2 · Red Edge en línea", de: "Engine v3.2 · Edge-Netzwerk online", it: "Engine v3.2 · Rete Edge online", ja: "エンジン v3.2 · エッジネットワーク稼働中", ko: "엔진 v3.2 · 엣지 네트워크 가동 중", tr: "Motor v3.2 · Edge Ağı Aktif", ar: "المحرك v3.2 · شبكة Edge متصلة", ru: "Движок v3.2 · Edge-сеть в сети" },
  hero_h1_1: { en: "Beyond Speed.", zh: "超越速度。", fr: "Au-delà de la vitesse.", es: "Más allá de la velocidad.", de: "Jenseits der Geschwindigkeit.", it: "Oltre la velocità.", ja: "速さを超えて。", ko: "속도를 넘어서.", tr: "Hızın Ötesinde.", ar: "ما وراء السرعة.", ru: "За пределами скорости." },
  hero_h1_2: { en: "Absolute Stealth.", zh: "绝对隐身。", fr: "Furtivité absolue.", es: "Sigilo absoluto.", de: "Absolute Tarnung.", it: "Furtività assoluta.", ja: "絶対的なステルス。", ko: "절대적 은신.", tr: "Mutlak Gizlilik.", ar: "تخفٍّ مُطلق.", ru: "Абсолютная скрытность." },
  hero_subtitle: { en: "The mirror-latency VPN engineered for the speed of light. Ultra-low latency. Up to 1000 Mbps per user. One tap to a planet-scale edge network.", zh: "为光速而生的镜像延迟 VPN。极低延迟，单用户最高 1000 Mbps 带宽，一键接入全球边缘网络。", fr: "Le VPN à miroir de latence conçu pour la vitesse de la lumière. Latence ultra-faible. Jusqu'à 1000 Mbps par utilisateur. Un clic, un réseau edge planétaire.", es: "El VPN de espejo de latencia diseñado para la velocidad de la luz. Latencia ultra-baja. Hasta 1000 Mbps por usuario. Un toque a una red edge planetaria.", de: "Das Spiegellatenz-VPN, gebaut für Lichtgeschwindigkeit. Ultra-niedrige Latenz. Bis zu 1000 Mbps pro Nutzer. Ein Tipp zum planetaren Edge-Netzwerk.", it: "La VPN a specchio di latenza progettata per la velocità della luce. Latenza ultra-bassa. Fino a 1000 Mbps per utente. Un tocco a una rete edge planetaria.", ja: "光速のために設計されたミラーレイテンシ VPN。超低遅延、ユーザーあたり最大 1000 Mbps、ワンタップで惑星規模のエッジネットワークへ。", ko: "빛의 속도를 위해 설계된 미러 레이턴시 VPN. 초저지연, 사용자당 최대 1000 Mbps, 원터치 글로벌 엣지 네트워크.", tr: "Işık hızı için tasarlanmış ayna-gecikme VPN. Ultra düşük gecikme. Kullanıcı başına 1000 Mbps'ye kadar. Tek dokunuşla küresel edge ağı.", ar: "VPN بانعكاس الكمون مُصمَّم لسرعة الضوء. زمن استجابة منخفض جدًا. حتى 1000 ميجابت/ثانية لكل مستخدم. لمسة واحدة لشبكة edge كوكبية.", ru: "VPN с зеркальной задержкой, созданный для скорости света. Сверхнизкий пинг. До 1000 Мбит/с на пользователя. Один тап до глобальной edge-сети." },
  hero_cta_primary: { en: "Download Now", zh: "立即下载", fr: "Télécharger", es: "Descargar", de: "Jetzt herunterladen", it: "Scarica ora", ja: "今すぐダウンロード", ko: "지금 다운로드", tr: "Hemen İndir", ar: "نزّل الآن", ru: "Скачать сейчас" },
  hero_cta_secondary: { en: "View Live Network", zh: "查看实时网络", fr: "Réseau en direct", es: "Ver red en vivo", de: "Live-Netzwerk ansehen", it: "Rete in tempo reale", ja: "ライブネットワーク", ko: "실시간 네트워크", tr: "Canlı Ağı Gör", ar: "الشبكة الحية", ru: "Сеть в реальном времени" },
  stat_users: { en: "Active Users", zh: "活跃用户", fr: "Utilisateurs actifs", es: "Usuarios activos", de: "Aktive Nutzer", it: "Utenti attivi", ja: "アクティブユーザー", ko: "활성 사용자", tr: "Aktif Kullanıcı", ar: "مستخدمون نشطون", ru: "Активные пользователи" },
  stat_edges: { en: "Global Edges", zh: "全球节点", fr: "Edges mondiaux", es: "Edges globales", de: "Globale Edges", it: "Edge globali", ja: "グローバルエッジ", ko: "글로벌 엣지", tr: "Küresel Edge", ar: "نقاط الحافة العالمية", ru: "Глобальные Edge" },
  stat_uptime: { en: "Uptime SLA", zh: "SLA 在线率", fr: "Disponibilité", es: "Tiempo de actividad", de: "Verfügbarkeit", it: "Disponibilità", ja: "稼働率 SLA", ko: "가동률 SLA", tr: "Çalışma Süresi", ar: "زمن التشغيل", ru: "SLA доступности" },
  stat_bandwidth: { en: "Per-User Max", zh: "单用户峰值", fr: "Max par utilisateur", es: "Máx. por usuario", de: "Max pro Nutzer", it: "Max per utente", ja: "ユーザー最大", ko: "사용자 최대", tr: "Kullanıcı Başına Max", ar: "الحد الأقصى للمستخدم", ru: "Макс. на пользователя" },

  // Hero canvas
  canvas_global_edge: { en: "Global Edge · Live", zh: "全球边缘 · 实时", fr: "Edge mondial · En direct", es: "Edge global · En vivo", de: "Globaler Edge · Live", it: "Edge globale · Live", ja: "グローバルエッジ · ライブ", ko: "글로벌 엣지 · 실시간", tr: "Küresel Edge · Canlı", ar: "edge عالمي · مباشر", ru: "Глобальный Edge · Live" },
  canvas_throughput: { en: "Throughput · Realtime", zh: "吞吐量 · 实时", fr: "Débit · Temps réel", es: "Rendimiento · Tiempo real", de: "Durchsatz · Echtzeit", it: "Throughput · Tempo reale", ja: "スループット · リアルタイム", ko: "처리량 · 실시간", tr: "Verim · Gerçek Zaman", ar: "الإنتاجية · فوري", ru: "Пропускная · Realtime" },
  canvas_latency: { en: "Latency", zh: "延迟", fr: "Latence", es: "Latencia", de: "Latenz", it: "Latenza", ja: "レイテンシ", ko: "지연 시간", tr: "Gecikme", ar: "زمن الاستجابة", ru: "Задержка" },
  canvas_ultralow: { en: "Ultra-low", zh: "极低", fr: "Ultra-faible", es: "Ultra-baja", de: "Ultra-niedrig", it: "Ultra-bassa", ja: "超低遅延", ko: "초저", tr: "Ultra Düşük", ar: "منخفض جداً", ru: "Сверхниз." },
  canvas_edges: { en: "Edges", zh: "节点", fr: "Edges", es: "Edges", de: "Edges", it: "Edge", ja: "エッジ", ko: "엣지", tr: "Edge", ar: "نقاط", ru: "Edge" },
  canvas_worldwide: { en: "20+ Worldwide", zh: "全球 20+", fr: "20+ Mondiaux", es: "20+ Mundial", de: "20+ Weltweit", it: "20+ Globali", ja: "世界20+", ko: "전 세계 20+", tr: "20+ Dünya Çapında", ar: "20+ حول العالم", ru: "20+ по миру" },
  canvas_peak: { en: "Per-User Peak", zh: "单用户峰值", fr: "Pic par utilisateur", es: "Pico por usuario", de: "Spitze pro Nutzer", it: "Picco per utente", ja: "ユーザー最大", ko: "사용자 최대", tr: "Kullanıcı Pik", ar: "ذروة المستخدم", ru: "Пик на польз." },

  // Onboarding
  ob_kicker: { en: "// Onboarding", zh: "// 接入流程", fr: "// Démarrage", es: "// Inicio", de: "// Einstieg", it: "// Avvio", ja: "// オンボーディング", ko: "// 온보딩", tr: "// Başlangıç", ar: "// البدء", ru: "// Старт" },
  ob_title_a: { en: "Up in", zh: "60 秒", fr: "Opérationnel en", es: "Listo en", de: "Bereit in", it: "Pronto in", ja: "わずか", ko: "단", tr: "Sadece", ar: "جاهز خلال", ru: "Готово за" },
  ob_title_b: { en: "60 seconds.", zh: "极速接入。", fr: "60 secondes.", es: "60 segundos.", de: "60 Sekunden.", it: "60 secondi.", ja: "60 秒で起動。", ko: "60 초.", tr: "60 saniye.", ar: "60 ثانية.", ru: "60 секунд." },
  ob_sub: { en: "From cold start to encrypted edge in three taps. Made for humans, engineered for engineers.", zh: "从冷启动到加密边缘，仅需三步。为人类设计，为工程师而造。", fr: "Du démarrage à froid à l'edge chiffré en trois clics. Conçu pour les humains, pensé pour les ingénieurs.", es: "Del arranque en frío al edge cifrado en tres toques. Hecho para humanos, diseñado para ingenieros.", de: "Vom Kaltstart zum verschlüsselten Edge in drei Taps. Für Menschen gemacht, für Ingenieure entwickelt.", it: "Da avvio a freddo a edge cifrato in tre tap. Fatto per umani, ingegnerizzato per ingegneri.", ja: "コールドスタートから暗号化エッジまで 3 タップ。人のために作り、エンジニアのために設計。", ko: "콜드 스타트에서 암호화 엣지까지 단 3 탭. 사람을 위해, 엔지니어가 만든.", tr: "Soğuk başlangıçtan şifreli edge'e üç dokunuşta. İnsanlar için yapıldı, mühendisler için tasarlandı.", ar: "من البداية الباردة إلى edge مُشفَّر في ثلاث نقرات. للإنسان، بهندسة المهندسين.", ru: "От холодного старта до зашифрованного edge — три тапа. Сделано для людей, спроектировано инженерами." },
  ob_s1_t: { en: "Download", zh: "下载", fr: "Téléchargez", es: "Descarga", de: "Herunterladen", it: "Scarica", ja: "ダウンロード", ko: "다운로드", tr: "İndir", ar: "تنزيل", ru: "Скачать" },
  ob_s1_d: { en: "Get MirrorSpeed for Android, HarmonyOS or Windows. Zero configuration.", zh: "支持 Android、HarmonyOS、Windows。零配置。", fr: "MirrorSpeed pour Android, HarmonyOS ou Windows. Zéro config.", es: "MirrorSpeed para Android, HarmonyOS o Windows. Cero configuración.", de: "MirrorSpeed für Android, HarmonyOS oder Windows. Null Konfiguration.", it: "MirrorSpeed per Android, HarmonyOS o Windows. Zero configurazioni.", ja: "Android · HarmonyOS · Windows 対応。設定不要。", ko: "Android, HarmonyOS, Windows 지원. 설정 불필요.", tr: "Android, HarmonyOS, Windows için MirrorSpeed. Sıfır kurulum.", ar: "MirrorSpeed لـ Android، HarmonyOS أو Windows. بدون إعداد.", ru: "MirrorSpeed для Android, HarmonyOS или Windows. Без настроек." },
  ob_s2_t: { en: "Register", zh: "注册", fr: "Inscription", es: "Regístrate", de: "Registrieren", it: "Registrati", ja: "登録", ko: "가입", tr: "Kayıt Ol", ar: "سجّل", ru: "Регистрация" },
  ob_s2_d: { en: "Sign up with just an email. No password required, no friction.", zh: "仅需邮箱注册，无需密码，无摩擦。", fr: "Inscription par email. Sans mot de passe, sans friction.", es: "Solo email. Sin contraseña, sin fricción.", de: "Anmeldung nur per E-Mail. Kein Passwort.", it: "Solo email. Nessuna password, nessun attrito.", ja: "メールだけで登録。パスワード不要、摩擦ゼロ。", ko: "이메일만으로 가입. 비밀번호 불필요.", tr: "Sadece e-posta. Şifre yok, engel yok.", ar: "سجّل بالبريد فقط. بدون كلمة مرور.", ru: "Регистрация по email. Без пароля, без трения." },
  ob_s3_t: { en: "Connect", zh: "连接", fr: "Connectez", es: "Conecta", de: "Verbinden", it: "Connetti", ja: "接続", ko: "연결", tr: "Bağlan", ar: "اتصل", ru: "Подключиться" },
  ob_s3_d: { en: "One tap connects you to the fastest edge. The engine handles the rest.", zh: "一键连接最快节点，引擎全自动处理。", fr: "Un clic vers l'edge le plus rapide. Le moteur s'occupe du reste.", es: "Un toque al edge más rápido. El motor hace el resto.", de: "Ein Tipp zum schnellsten Edge. Die Engine erledigt den Rest.", it: "Un tap all'edge più veloce. Il motore fa il resto.", ja: "ワンタップで最速エッジへ。あとはエンジンが処理。", ko: "한 번 탭으로 가장 빠른 엣지에. 엔진이 알아서.", tr: "Tek dokunuşla en hızlı edge. Gerisini motor halleder.", ar: "نقرة واحدة إلى أسرع edge. والمحرك يهتم بالباقي.", ru: "Один тап до быстрейшего edge. Движок сделает остальное." },

  // Features
  feat_kicker: { en: "// Why MirrorSpeed", zh: "// 为何选择 MirrorSpeed", fr: "// Pourquoi MirrorSpeed", es: "// Por qué MirrorSpeed", de: "// Warum MirrorSpeed", it: "// Perché MirrorSpeed", ja: "// なぜ MirrorSpeed か", ko: "// 왜 MirrorSpeed인가", tr: "// Neden MirrorSpeed", ar: "// لماذا MirrorSpeed", ru: "// Почему MirrorSpeed" },
  feat_h1: { en: "Engineered for the", zh: "为光速而", fr: "Conçu pour la", es: "Diseñado para la", de: "Gebaut für die", it: "Progettato per la", ja: "光速のために", ko: "빛의 속도를", tr: "Işık hızı için", ar: "هندسة من أجل", ru: "Создано для" },
  feat_h2: { en: "speed of light.", zh: "工程。", fr: "vitesse de la lumière.", es: "velocidad de la luz.", de: "Lichtgeschwindigkeit.", it: "velocità della luce.", ja: "設計。", ko: "위해 설계.", tr: "tasarlandı.", ar: "سرعة الضوء.", ru: "скорости света." },
  feat_sub: { en: "We don't tunnel. We mirror. Our in-house engine reflects packets at near-physical limits — keeping latency low and traffic invisible.", zh: "我们不做隧道，我们做镜像。自研引擎将数据包反射至接近物理极限——延迟更低，流量不可见。", fr: "Nous ne tunnelons pas. Nous reflétons. Notre moteur maison reflète les paquets à la limite physique — faible latence, trafic invisible.", es: "No hacemos túnel. Espejamos. Nuestro motor refleja paquetes en el límite físico — baja latencia, tráfico invisible.", de: "Wir tunneln nicht. Wir spiegeln. Unsere Engine reflektiert Pakete nahe der physikalischen Grenze — niedrige Latenz, unsichtbarer Traffic.", it: "Non facciamo tunnel. Specchiamo. Il nostro motore riflette pacchetti al limite fisico — bassa latenza, traffico invisibile.", ja: "我々はトンネルしない。ミラーする。自社エンジンが物理限界に近い速度でパケットを反射 — 低レイテンシ、不可視のトラフィック。", ko: "우리는 터널링하지 않습니다. 미러링합니다. 자체 엔진이 물리적 한계에 가깝게 패킷을 반사합니다.", tr: "Tünel açmıyoruz. Yansıtıyoruz. Kendi motorumuz paketleri fiziksel sınıra yakın yansıtır — düşük gecikme, görünmez trafik.", ar: "نحن لا نُنفِق. نحن نعكس. محركنا الداخلي يعكس الحزم قرب الحد الفيزيائي — تأخير منخفض، حركة مرور خفية.", ru: "Мы не туннелируем. Мы зеркалим. Наш движок отражает пакеты на пределе физики — низкая задержка, невидимый трафик." },
  feat_proprietary: { en: "Proprietary Core", zh: "自研内核", fr: "Cœur propriétaire", es: "Núcleo propio", de: "Eigene Engine", it: "Motore proprietario", ja: "独自コア", ko: "독자 엔진", tr: "Özel Çekirdek", ar: "نواة خاصة", ru: "Свой движок" },
  feat_proprietary_d: { en: "Dynamic encryption engine. Fast, stealthy, audited.", zh: "动态加密引擎，快速、隐身、已审计。", fr: "Moteur de chiffrement dynamique. Rapide, furtif, audité.", es: "Motor de cifrado dinámico. Rápido, sigiloso, auditado.", de: "Dynamische Verschlüsselungsengine. Schnell, getarnt, geprüft.", it: "Motore di cifratura dinamica. Veloce, furtivo, certificato.", ja: "動的暗号化エンジン。速く、隠密、監査済み。", ko: "동적 암호화 엔진. 빠르고, 은밀하며, 감사 완료.", tr: "Dinamik şifreleme motoru. Hızlı, gizli, denetlenmiş.", ar: "محرك تشفير ديناميكي. سريع، خفي، مُدقَّق.", ru: "Динамичное шифрование. Быстро, скрытно, проверено." },
  feat_zerologs: { en: "Zero Logs", zh: "零日志", fr: "Zéro logs", es: "Sin registros", de: "Keine Logs", it: "Zero Log", ja: "ノーログ", ko: "무로그", tr: "Sıfır Log", ar: "بدون سجلات", ru: "Без логов" },
  feat_zerologs_d: { en: "Independently audited.", zh: "独立审计。", fr: "Audité indépendamment.", es: "Auditado independiente.", de: "Unabhängig geprüft.", it: "Verificato indipendentemente.", ja: "第三者監査済み。", ko: "독립 감사 완료.", tr: "Bağımsız denetlendi.", ar: "مُدقَّق مستقلًا.", ru: "Независимая проверка." },
  feat_multi: { en: "Multi-Platform", zh: "多平台", fr: "Multi-plateforme", es: "Multi-plataforma", de: "Multi-Plattform", it: "Multi-piattaforma", ja: "マルチプラットフォーム", ko: "다중 플랫폼", tr: "Çoklu Platform", ar: "متعدد المنصات", ru: "Мультиплатформа" },
  feat_multi_d: { en: "Android · Windows · HarmonyOS", zh: "Android · Windows · HarmonyOS", fr: "Android · Windows · HarmonyOS", es: "Android · Windows · HarmonyOS", de: "Android · Windows · HarmonyOS", it: "Android · Windows · HarmonyOS", ja: "Android · Windows · HarmonyOS", ko: "Android · Windows · HarmonyOS", tr: "Android · Windows · HarmonyOS", ar: "Android · Windows · HarmonyOS", ru: "Android · Windows · HarmonyOS" },
  feat_switch: { en: "Free Switching", zh: "自由切换", fr: "Bascule libre", es: "Cambio libre", de: "Freier Wechsel", it: "Switch libero", ja: "自由切替", ko: "자유 전환", tr: "Serbest Geçiş", ar: "تبديل حرّ", ru: "Свободный выбор" },
  feat_switch_d: { en: "Hop between 20+ edges, anytime. Free tier available.", zh: "随时切换 20+ 节点。提供免费套餐。", fr: "Sautez entre 20+ edges, à tout moment. Offre gratuite disponible.", es: "Salta entre 20+ edges. Nivel gratuito disponible.", de: "Wechsle zwischen 20+ Edges. Free-Tier verfügbar.", it: "Salta tra 20+ edge. Piano gratuito disponibile.", ja: "20+ エッジを自由に往復。無料プランあり。", ko: "20+ 엣지 자유 전환. 무료 플랜 제공.", tr: "20+ edge arasında geçiş. Ücretsiz plan mevcut.", ar: "تنقّل بين 20+ نقطة. خطة مجانية متاحة.", ru: "Между 20+ edge. Есть бесплатный тариф." },
  feat_global: { en: "Global Edge", zh: "全球边缘", fr: "Edge mondial", es: "Edge global", de: "Globaler Edge", it: "Edge globale", ja: "グローバルエッジ", ko: "글로벌 엣지", tr: "Küresel Edge", ar: "edge عالمي", ru: "Глобальный Edge" },
  feat_global_d: { en: "Asia · Americas · Europe, and more to come.", zh: "亚洲 · 美洲 · 欧洲，更多即将上线。", fr: "Asie · Amériques · Europe, et plus à venir.", es: "Asia · Américas · Europa, y más por venir.", de: "Asien · Amerika · Europa, weitere folgen.", it: "Asia · Americhe · Europa, e altro in arrivo.", ja: "アジア · 米州 · 欧州、続々追加予定。", ko: "아시아 · 미주 · 유럽, 더 늘어납니다.", tr: "Asya · Amerika · Avrupa, dahası geliyor.", ar: "آسيا · الأمريكتان · أوروبا، والمزيد قريبًا.", ru: "Азия · Америка · Европа, и больше скоро." },
  feat_engine: { en: "In-House Engine", zh: "自研引擎", fr: "Moteur maison", es: "Motor propio", de: "Eigene Engine", it: "Motore proprietario", ja: "自社エンジン", ko: "자체 엔진", tr: "Kendi Motor", ar: "محرّك خاص", ru: "Свой движок" },
  feat_engine_d: { en: "UDP encapsulation by default — far faster and more efficient than TCP-based tools.", zh: "默认 UDP 协议封装，加速速度和效率远超基于 TCP 的工具。", fr: "Encapsulation UDP par défaut — bien plus rapide et efficace que les outils TCP.", es: "Encapsulación UDP por defecto — mucho más rápido y eficiente que herramientas TCP.", de: "Standard-UDP-Kapselung — deutlich schneller und effizienter als TCP-basierte Tools.", it: "Incapsulamento UDP di default — molto più veloce ed efficiente degli strumenti TCP.", ja: "デフォルトで UDP カプセル化 — TCP ベースのツールより遥かに高速・高効率。", ko: "기본 UDP 캡슐화 — TCP 기반 도구보다 훨씬 빠르고 효율적입니다.", tr: "Varsayılan UDP kapsülleme — TCP tabanlı araçlardan çok daha hızlı ve verimli.", ar: "تغليف UDP افتراضيًا — أسرع وأكثر كفاءة بكثير من أدوات TCP.", ru: "UDP-инкапсуляция по умолчанию — гораздо быстрее и эффективнее TCP-инструментов." },
  feat_unlimited: { en: "Unlimited Traffic", zh: "不限流量", fr: "Trafic illimité", es: "Tráfico ilimitado", de: "Unbegrenzter Traffic", it: "Traffico illimitato", ja: "通信量無制限", ko: "무제한 트래픽", tr: "Sınırsız Trafik", ar: "حركة بيانات غير محدودة", ru: "Безлимит трафика" },
  feat_unlimited_d: { en: "Stream the global edge with zero traffic caps.", zh: "畅连全球边缘，没有流量限制。", fr: "Streamez l'edge mondial sans aucun plafond.", es: "Disfruta del edge global sin límites de tráfico.", de: "Nutze den globalen Edge ohne Datenlimit.", it: "Usa l'edge globale senza limiti di traffico.", ja: "グローバルエッジを通信量制限なしで。", ko: "글로벌 엣지를 트래픽 제한 없이.", tr: "Küresel edge'de trafik sınırı yok.", ar: "تدفّق على edge العالمي بلا حدود.", ru: "Глобальный edge без ограничений по трафику." },
  feat_support: { en: "24/7 Support", zh: "全天候支持", fr: "Support 24/7", es: "Soporte 24/7", de: "24/7 Support", it: "Supporto 24/7", ja: "24/7 サポート", ko: "24/7 지원", tr: "7/24 Destek", ar: "دعم 24/7", ru: "Поддержка 24/7" },
  feat_support_d: { en: "Real engineers. Real answers. No bots.", zh: "真人工程师，真实答案，无机器人。", fr: "Ingénieurs réels. Vraies réponses. Pas de bots.", es: "Ingenieros reales. Respuestas reales. Sin bots.", de: "Echte Ingenieure. Echte Antworten. Keine Bots.", it: "Veri ingegneri. Vere risposte. No bot.", ja: "本物のエンジニア。本物の答え。ボットなし。", ko: "진짜 엔지니어. 진짜 답변. 봇 없음.", tr: "Gerçek mühendisler. Gerçek cevaplar. Bot yok.", ar: "مهندسون حقيقيون. إجابات حقيقية. بلا روبوتات.", ru: "Живые инженеры. Реальные ответы. Без ботов." },

  // Network / global
  net_kicker: { en: "// Global Network", zh: "// 全球网络", fr: "// Réseau mondial", es: "// Red global", de: "// Globales Netzwerk", it: "// Rete globale", ja: "// グローバルネットワーク", ko: "// 글로벌 네트워크", tr: "// Küresel Ağ", ar: "// شبكة عالمية", ru: "// Глобальная сеть" },
  net_h1: { en: "A planet of", zh: "整个", fr: "Une planète d'", es: "Un planeta de", de: "Ein Planet voller", it: "Un pianeta di", ja: "惑星規模の", ko: "행성 규모의", tr: "Bir gezegen dolusu", ar: "كوكب من", ru: "Планета из" },
  net_h2: { en: "edges.", zh: "地球的边缘节点。", fr: "edges.", es: "edges.", de: "Edges.", it: "edge.", ja: "エッジ。", ko: "엣지.", tr: "edge.", ar: "نقاط edge.", ru: "edge-узлов." },
  net_sub: { en: "Edge nodes blanket Asia, the Americas, and Europe — your traffic always finds the nearest, fastest hop. No configuration. No thinking.", zh: "节点遍布亚洲、美洲、欧洲——流量永远走最近、最快的一跳。零配置，零思考。", fr: "Des nœuds edge couvrent l'Asie, les Amériques et l'Europe — votre trafic prend toujours le saut le plus court. Sans config, sans réflexion.", es: "Nodos edge cubren Asia, las Américas y Europa — tu tráfico siempre toma el salto más cercano. Sin config, sin pensar.", de: "Edge-Nodes überziehen Asien, Amerika und Europa — Dein Traffic findet immer den nächsten, schnellsten Hop.", it: "Nodi edge coprono Asia, Americhe ed Europa — il tuo traffico trova sempre l'hop più vicino.", ja: "エッジノードがアジア・米州・欧州を覆う — トラフィックは常に最寄りで最速のホップへ。", ko: "엣지 노드가 아시아·미주·유럽을 뒤덮습니다 — 트래픽은 항상 가장 가깝고 빠른 홉으로.", tr: "Edge düğümleri Asya, Amerika ve Avrupa'yı kaplar — trafiğin her zaman en yakın ve en hızlı sıçramayı bulur.", ar: "نقاط edge تغطي آسيا والأمريكتين وأوروبا — حركة المرور دائمًا تختار أقرب وأسرع قفزة.", ru: "Edge-узлы покрывают Азию, Америку и Европу — ваш трафик всегда найдёт ближайший быстрый прыжок." },
  net_live: { en: "Network Live", zh: "网络在线", fr: "Réseau en direct", es: "Red en vivo", de: "Netzwerk Live", it: "Rete Live", ja: "ネットワーク稼働中", ko: "네트워크 가동", tr: "Ağ Canlı", ar: "شبكة حية", ru: "Сеть в сети" },
  net_pulse: { en: "Pulse / 1.4s", zh: "脉冲 / 1.4 秒", fr: "Pulse / 1,4s", es: "Pulso / 1.4s", de: "Puls / 1,4s", it: "Pulse / 1,4s", ja: "パルス / 1.4 秒", ko: "펄스 / 1.4초", tr: "Nabız / 1.4 sn", ar: "نبض / 1.4 ث", ru: "Пульс / 1.4с" },
  net_americas: { en: "Americas", zh: "美洲", fr: "Amériques", es: "Américas", de: "Amerika", it: "Americhe", ja: "米州", ko: "미주", tr: "Amerika", ar: "الأمريكتان", ru: "Америка" },
  net_europe: { en: "Europe", zh: "欧洲", fr: "Europe", es: "Europa", de: "Europa", it: "Europa", ja: "欧州", ko: "유럽", tr: "Avrupa", ar: "أوروبا", ru: "Европа" },
  net_asia: { en: "Asia", zh: "亚洲", fr: "Asie", es: "Asia", de: "Asien", it: "Asia", ja: "アジア", ko: "아시아", tr: "Asya", ar: "آسيا", ru: "Азия" },
  net_online: { en: "Online", zh: "在线", fr: "En ligne", es: "En línea", de: "Online", it: "Online", ja: "オンライン", ko: "온라인", tr: "Çevrimiçi", ar: "متصل", ru: "Онлайн" },
  net_kpi1: { en: "Global edges", zh: "全球节点", fr: "Edges mondiaux", es: "Edges globales", de: "Globale Edges", it: "Edge globali", ja: "グローバルエッジ", ko: "글로벌 엣지", tr: "Küresel edge", ar: "نقاط عالمية", ru: "Глобальные edge" },
  net_kpi1s: { en: "Asia · Americas · Europe", zh: "亚洲 · 美洲 · 欧洲", fr: "Asie · Amériques · Europe", es: "Asia · Américas · Europa", de: "Asien · Amerika · Europa", it: "Asia · Americhe · Europa", ja: "アジア · 米州 · 欧州", ko: "아시아 · 미주 · 유럽", tr: "Asya · Amerika · Avrupa", ar: "آسيا · الأمريكتان · أوروبا", ru: "Азия · Америка · Европа" },
  net_kpi2v: { en: "1000 Mbps", zh: "1000 Mbps", fr: "1000 Mbps", es: "1000 Mbps", de: "1000 Mbps", it: "1000 Mbps", ja: "1000 Mbps", ko: "1000 Mbps", tr: "1000 Mbps", ar: "1000 ميغابت/ث", ru: "1000 Мбит/с" },
  net_kpi2: { en: "Per-user max bandwidth", zh: "单用户最大带宽", fr: "Bande passante max / utilisateur", es: "Ancho de banda máx. por usuario", de: "Max. Bandbreite pro Nutzer", it: "Banda max per utente", ja: "ユーザー最大帯域", ko: "사용자 최대 대역폭", tr: "Kullanıcı başına max bant", ar: "أقصى عرض حزمة لكل مستخدم", ru: "Макс. полоса на пользователя" },
  net_kpi2s: { en: "Burst-ready, line-rate ready", zh: "可突发，可线速", fr: "Burst, ligne complète", es: "Listo para ráfagas y línea completa", de: "Burst- und Line-Rate-fähig", it: "Pronto a burst e line-rate", ja: "バースト・ラインレート対応", ko: "버스트·라인레이트 대응", tr: "Burst ve hat hızı için hazır", ar: "جاهز للذروة وللتدفق الكامل", ru: "Burst и line-rate" },
  net_kpi3: { en: "Uptime SLA", zh: "在线率 SLA", fr: "Disponibilité SLA", es: "SLA de disponibilidad", de: "Verfügbarkeits-SLA", it: "SLA disponibilità", ja: "稼働率 SLA", ko: "가동률 SLA", tr: "Çalışma SLA", ar: "SLA التشغيل", ru: "SLA доступности" },
  net_kpi3s: { en: "Engineered for always-on", zh: "为永远在线而生", fr: "Conçu pour le toujours-en-ligne", es: "Diseñado para estar siempre activo", de: "Für Dauerbetrieb gebaut", it: "Progettato per sempre-attivo", ja: "常時稼働のために設計", ko: "상시 가동을 위해 설계", tr: "Daima açık için tasarlandı", ar: "مُهندَس للعمل الدائم", ru: "Создано для always-on" },

  // Testimonials
  test_kicker: { en: "// Field Reports", zh: "// 用户实测", fr: "// Témoignages", es: "// Reportes", de: "// Stimmen", it: "// Testimonianze", ja: "// 利用者の声", ko: "// 사용자 후기", tr: "// Kullanıcı", ar: "// آراء", ru: "// Отзывы" },
  test_h1: { en: "Trusted by", zh: "已被", fr: "Adopté par", es: "Confían en nosotros", de: "Vertraut von", it: "Scelto da", ja: "信頼", ko: "신뢰", tr: "Güveniliyor:", ar: "موثوق من", ru: "Доверяют" },
  test_h2: { en: "100,000+", zh: "100,000+ 用户", fr: "100 000+", es: "100,000+", de: "100.000+", it: "100.000+", ja: "10万+", ko: "10만+", tr: "100.000+", ar: "100,000+", ru: "100 000+" },
  test_sub: { en: "Real users. Real speeds. Real talk.", zh: "真实用户，真实速度，真实评价。", fr: "Vrais utilisateurs. Vraies vitesses. Vrais avis.", es: "Usuarios reales. Velocidades reales.", de: "Echte Nutzer. Echte Geschwindigkeit.", it: "Veri utenti. Vere velocità.", ja: "本物のユーザー。本物の速度。", ko: "진짜 사용자. 진짜 속도.", tr: "Gerçek kullanıcı. Gerçek hız.", ar: "مستخدمون حقيقيون. سرعات حقيقية.", ru: "Реальные пользователи. Реальные скорости." },

  // Pricing
  pr_kicker: { en: "// Pricing", zh: "// 价格", fr: "// Tarifs", es: "// Precios", de: "// Preise", it: "// Prezzi", ja: "// 料金", ko: "// 요금", tr: "// Fiyatlar", ar: "// التسعير", ru: "// Цены" },
  pr_h1: { en: "Global access.", zh: "全球访问。", fr: "Accès mondial.", es: "Acceso global.", de: "Globaler Zugang.", it: "Accesso globale.", ja: "グローバルアクセス。", ko: "글로벌 액세스.", tr: "Küresel erişim.", ar: "وصول عالمي.", ru: "Глобальный доступ." },
  pr_h2: { en: "Local price.", zh: "本地价格。", fr: "Prix local.", es: "Precio local.", de: "Lokaler Preis.", it: "Prezzo locale.", ja: "ローカル価格。", ko: "로컬 가격.", tr: "Yerel fiyat.", ar: "بسعرٍ محلي.", ru: "Местная цена." },
  pr_sub: { en: "Less than a cup of coffee. Cancel anytime. 7-day money-back guarantee.", zh: "比一杯咖啡还便宜，随时取消，7 天无理由退款。", fr: "Moins qu'un café. Annulez quand vous voulez. Garantie 7 jours.", es: "Menos que un café. Cancela cuando quieras. Garantía 7 días.", de: "Weniger als ein Kaffee. Jederzeit kündbar. 7 Tage Rückgabe.", it: "Meno di un caffè. Annulla quando vuoi. Garanzia 7 giorni.", ja: "コーヒー一杯より安い。いつでも解約。7 日間返金保証。", ko: "커피 한 잔보다 저렴. 언제든 해지. 7일 환불 보장.", tr: "Bir kahveden ucuz. İstediğin zaman iptal. 7 gün iade.", ar: "أقل من فنجان قهوة. إلغاء في أي وقت. ضمان 7 أيام.", ru: "Дешевле чашки кофе. Отмена в любой момент. 7 дней возврата." },
  pr_monthly: { en: "Monthly", zh: "月度", fr: "Mensuel", es: "Mensual", de: "Monatlich", it: "Mensile", ja: "月額", ko: "월간", tr: "Aylık", ar: "شهري", ru: "Месячный" },
  pr_quarterly: { en: "Quarterly", zh: "季付", fr: "Trimestriel", es: "Trimestral", de: "Quartalsweise", it: "Trimestrale", ja: "四半期", ko: "분기", tr: "Üç Aylık", ar: "ربع سنوي", ru: "Квартальный" },
  pr_halfyear: { en: "Half-Year", zh: "半年付", fr: "Semestriel", es: "Semestral", de: "Halbjährlich", it: "Semestrale", ja: "半年", ko: "반기", tr: "Altı Aylık", ar: "نصف سنوي", ru: "Полугодовой" },
  pr_2yr: { en: "2-Year Plan", zh: "两年付", fr: "Plan 2 ans", es: "Plan 2 años", de: "2-Jahres-Plan", it: "Piano 2 anni", ja: "2 年プラン", ko: "2년 플랜", tr: "2 Yıllık Plan", ar: "خطة سنتين", ru: "План на 2 года" },
  pr_yearly: { en: "Yearly", zh: "年付", fr: "Annuel", es: "Anual", de: "Jährlich", it: "Annuale", ja: "年額", ko: "연간", tr: "Yıllık", ar: "سنوي", ru: "Годовой" },
  pr_monthly_short: { en: "/mo", zh: "/月", fr: "/mois", es: "/mes", de: "/Mt", it: "/mese", ja: "/月", ko: "/월", tr: "/ay", ar: "/شهر", ru: "/мес" },
  pr_save_word: { en: "Save", zh: "立省", fr: "Économisez", es: "Ahorra", de: "Spare", it: "Risparmia", ja: "節約", ko: "절약", tr: "Tasarruf", ar: "وفّر", ru: "Скидка" },
  pr_popular: { en: "MOST POPULAR", zh: "最受欢迎", fr: "LE PLUS POPULAIRE", es: "MÁS POPULAR", de: "AM BELIEBTESTEN", it: "PIÙ POPOLARE", ja: "一番人気", ko: "가장 인기", tr: "EN POPÜLER", ar: "الأكثر شعبية", ru: "ПОПУЛЯРНЫЙ" },
  pr_save: { en: "Save 58%", zh: "立省 58%", fr: "Économisez 58 %", es: "Ahorra 58 %", de: "Spare 58 %", it: "Risparmia 58%", ja: "58% お得", ko: "58% 절약", tr: "%58 Tasarruf", ar: "وفّر 58%", ru: "Скидка 58%" },
  pr_billed_m: { en: "Billed monthly", zh: "按月扣费", fr: "Facturé mensuellement", es: "Facturado mensual", de: "Monatlich abgerechnet", it: "Fatturato al mese", ja: "月毎課金", ko: "월별 청구", tr: "Aylık fatura", ar: "فاتورة شهرية", ru: "Ежемесячно" },
  pr_billed_q: { en: "Billed every 3 months", zh: "每 3 个月扣费", fr: "Tous les 3 mois", es: "Cada 3 meses", de: "Alle 3 Monate", it: "Ogni 3 mesi", ja: "3 ヶ月毎", ko: "3개월마다", tr: "3 ayda bir", ar: "كل 3 أشهر", ru: "Каждые 3 мес." },
  pr_billed_h: { en: "Billed every 6 months", zh: "每 6 个月扣费", fr: "Tous les 6 mois", es: "Cada 6 meses", de: "Alle 6 Monate", it: "Ogni 6 mesi", ja: "6 ヶ月毎", ko: "6개월마다", tr: "6 ayda bir", ar: "كل 6 أشهر", ru: "Каждые 6 мес." },
  pr_billed_2y: { en: "Billed every 24 months", zh: "每 24 个月扣费", fr: "Tous les 24 mois", es: "Cada 24 meses", de: "Alle 24 Monate", it: "Ogni 24 mesi", ja: "24 ヶ月毎", ko: "24개월마다", tr: "24 ayda bir", ar: "كل 24 شهر", ru: "Каждые 24 мес." },
  pr_billed_y: { en: "Billed annually", zh: "按年扣费", fr: "Facturé annuellement", es: "Facturado anual", de: "Jährlich abgerechnet", it: "Fatturato annuale", ja: "年毎課金", ko: "연간 청구", tr: "Yıllık fatura", ar: "فاتورة سنوية", ru: "Ежегодно" },
  perk_locations: { en: "All 20+ global locations", zh: "全部 20+ 全球节点", fr: "Toutes les 20+ locations", es: "Las 20+ ubicaciones globales", de: "Alle 20+ Standorte", it: "Tutte le 20+ posizioni", ja: "20+ 拠点すべて", ko: "전 세계 20+ 지역", tr: "20+ küresel konum", ar: "جميع 20+ موقعاً", ru: "Все 20+ локаций" },
  perk_encryption: { en: "Proprietary dynamic encryption", zh: "自研动态加密", fr: "Chiffrement dynamique propriétaire", es: "Cifrado dinámico propio", de: "Eigene dynamische Verschlüsselung", it: "Cifratura dinamica proprietaria", ja: "独自動的暗号化", ko: "독자 동적 암호화", tr: "Özel dinamik şifreleme", ar: "تشفير ديناميكي خاص", ru: "Своё динамическое шифрование" },
  perk_devices: { en: "Up to 3 devices simultaneously", zh: "最多同时 3 台设备", fr: "Jusqu'à 3 appareils simultanés", es: "Hasta 3 dispositivos a la vez", de: "Bis zu 3 Geräte gleichzeitig", it: "Fino a 3 dispositivi insieme", ja: "同時 3 台まで", ko: "동시 최대 3대", tr: "Aynı anda 3 cihaza kadar", ar: "حتى 3 أجهزة في وقتٍ واحد", ru: "До 3 устройств одновременно" },
  perk_bw: { en: "Up to 1000 Mbps per user", zh: "单用户最高 1000 Mbps", fr: "Jusqu'à 1000 Mbps par utilisateur", es: "Hasta 1000 Mbps por usuario", de: "Bis 1000 Mbps pro Nutzer", it: "Fino a 1000 Mbps per utente", ja: "ユーザー毎 1000 Mbps まで", ko: "사용자당 최대 1000 Mbps", tr: "Kullanıcı başına 1000 Mbps'ye kadar", ar: "حتى 1000 ميغابت/ث للمستخدم", ru: "До 1000 Мбит/с на пользователя" },
  perk_support: { en: "24/7 engineer support", zh: "7×24 工程师支持", fr: "Support ingénieur 24/7", es: "Soporte ingeniero 24/7", de: "24/7 Ingenieur-Support", it: "Supporto ingegnere 24/7", ja: "24/7 エンジニアサポート", ko: "24/7 엔지니어 지원", tr: "7/24 mühendis desteği", ar: "دعم مهندس 24/7", ru: "Поддержка инженеров 24/7" },
  perk_cancel: { en: "Cancel anytime", zh: "随时取消", fr: "Annulez à tout moment", es: "Cancela cuando quieras", de: "Jederzeit kündbar", it: "Annulla quando vuoi", ja: "いつでも解約", ko: "언제든 해지", tr: "İstediğin zaman iptal", ar: "إلغاء في أي وقت", ru: "Отмена в любой момент" },
  pr_select: { en: "Select Plan", zh: "选择该方案", fr: "Choisir", es: "Elegir plan", de: "Plan wählen", it: "Scegli piano", ja: "プラン選択", ko: "플랜 선택", tr: "Planı Seç", ar: "اختر الخطة", ru: "Выбрать" },
  trust_refund: { en: "7-day refund", zh: "7 天退款", fr: "Remb. 7 jours", es: "Reembolso 7 días", de: "7 Tage Rückgabe", it: "Rimborso 7 giorni", ja: "7 日返金", ko: "7일 환불", tr: "7 gün iade", ar: "استرداد 7 أيام", ru: "Возврат 7 дней" },
  trust_checkout: { en: "Encrypted checkout", zh: "加密结账", fr: "Paiement chiffré", es: "Pago cifrado", de: "Verschlüsselter Checkout", it: "Checkout cifrato", ja: "暗号化決済", ko: "암호화 결제", tr: "Şifreli ödeme", ar: "دفع مُشفَّر", ru: "Шифр. оплата" },
  trust_instant: { en: "Instant activation", zh: "即时开通", fr: "Activation instantanée", es: "Activación instantánea", de: "Sofort aktiv", it: "Attivazione istantanea", ja: "即時有効化", ko: "즉시 활성화", tr: "Anında aktif", ar: "تفعيل فوري", ru: "Мгнов. активация" },

  // FAQ
  faq_kicker: { en: "// FAQ", zh: "// 常见问题", fr: "// FAQ", es: "// FAQ", de: "// FAQ", it: "// FAQ", ja: "// よくある質問", ko: "// 자주 묻는 질문", tr: "// SSS", ar: "// الأسئلة", ru: "// FAQ" },
  faq_h1: { en: "Frequently", zh: "常见", fr: "Questions", es: "Preguntas", de: "Häufig", it: "Domande", ja: "よくある", ko: "자주 묻는", tr: "Sık sorulan", ar: "أسئلة", ru: "Часто" },
  faq_h2: { en: "asked.", zh: "问题。", fr: "fréquentes.", es: "frecuentes.", de: "gefragt.", it: "frequenti.", ja: "ご質問。", ko: "질문.", tr: "sorular.", ar: "متكررة.", ru: "задаваемые." },
  faq_q1: { en: "How fast is MirrorSpeed?", zh: "MirrorSpeed 有多快？", fr: "Quelle est la vitesse de MirrorSpeed ?", es: "¿Qué tan rápido es MirrorSpeed?", de: "Wie schnell ist MirrorSpeed?", it: "Quanto è veloce MirrorSpeed?", ja: "MirrorSpeed の速度は？", ko: "MirrorSpeed는 얼마나 빠른가요?", tr: "MirrorSpeed ne kadar hızlı?", ar: "ما مدى سرعة MirrorSpeed؟", ru: "Насколько быстр MirrorSpeed?" },
  faq_a1: { en: "Ultra-low latency to the nearest edge, with per-user bandwidth up to 1000 Mbps. Our in-house mirror engine eliminates traditional VPN overhead so it feels native, not tunneled.", zh: "到最近节点延迟极低，单用户带宽最高 1000 Mbps。自研镜像引擎消除了传统 VPN 的开销，使用感如直连。", fr: "Latence ultra-faible vers l'edge le plus proche, bande passante jusqu'à 1000 Mbps par utilisateur. Notre moteur miroir élimine la surcharge VPN — on dirait du natif.", es: "Latencia ultra-baja al edge más cercano, hasta 1000 Mbps por usuario. Nuestro motor espejo elimina la sobrecarga VPN.", de: "Ultra-niedrige Latenz zum nächsten Edge, bis 1000 Mbps pro Nutzer. Unsere Spiegel-Engine eliminiert VPN-Overhead.", it: "Latenza ultra-bassa verso l'edge più vicino, fino a 1000 Mbps per utente. Il nostro motore specchio elimina l'overhead VPN.", ja: "最寄りエッジへの超低レイテンシ、ユーザー毎最大 1000 Mbps。自社ミラーエンジンが従来 VPN のオーバーヘッドを排除。", ko: "가장 가까운 엣지까지 초저지연, 사용자당 최대 1000 Mbps. 자체 미러 엔진이 VPN 오버헤드를 제거합니다.", tr: "En yakın edge'e ultra düşük gecikme, kullanıcı başına 1000 Mbps'ye kadar. Ayna motorumuz klasik VPN yükünü ortadan kaldırır.", ar: "زمن استجابة منخفض جدًا إلى أقرب edge، حتى 1000 ميغابت/ث للمستخدم. محرك المرآة لدينا يلغي حِمل VPN التقليدي.", ru: "Сверхниз. задержка до ближайшего edge, до 1000 Мбит/с на пользователя. Наш зеркальный движок убирает оверхед VPN." },
  faq_q2: { en: "Do you keep logs?", zh: "你们会保留日志吗？", fr: "Conservez-vous des logs ?", es: "¿Guardan registros?", de: "Speichert ihr Logs?", it: "Tenete log?", ja: "ログを保存しますか？", ko: "로그를 보관하나요?", tr: "Log tutuyor musunuz?", ar: "هل تحتفظون بسجلات؟", ru: "Храните ли вы логи?" },
  faq_a2: { en: "No. Independently audited zero-logs policy — we cannot see your traffic even if we wanted to.", zh: "不会。独立审计的零日志政策——即使我们想看也看不到您的流量。", fr: "Non. Politique zéro log auditée — nous ne pouvons pas voir votre trafic.", es: "No. Política de cero registros auditada — no podemos ver tu tráfico.", de: "Nein. Unabhängig geprüfte Zero-Logs-Richtlinie.", it: "No. Politica zero log certificata.", ja: "いいえ。第三者監査済みのノーログ。", ko: "아니요. 독립 감사를 거친 무로그 정책.", tr: "Hayır. Bağımsız denetlenmiş sıfır-log politikası.", ar: "لا. سياسة عدم احتفاظ بالسجلات، مُدقَّقة مستقلًا.", ru: "Нет. Независимо проверенная политика без логов." },
  faq_q3: { en: "Which clients work?", zh: "支持哪些客户端？", fr: "Quels clients sont compatibles ?", es: "¿Qué clientes funcionan?", de: "Welche Clients funktionieren?", it: "Quali client supportate?", ja: "対応クライアントは？", ko: "어떤 클라이언트가 지원되나요?", tr: "Hangi istemciler destekleniyor?", ar: "ما هي العملاء المدعومين؟", ru: "Какие клиенты работают?" },
  faq_a3: { en: "Native apps for Android, HarmonyOS, and Windows today. Compatibility planned for WireGuard / Clash-compatible clients across Mac, iOS, Linux and OpenWrt.", zh: "目前提供 Android、HarmonyOS、Windows 原生应用，未来支持 WireGuard / Clash 兼容客户端（Mac / iOS / Linux / OpenWrt）。", fr: "Apps natives Android, HarmonyOS, Windows. Bientôt WireGuard / Clash (Mac/iOS/Linux/OpenWrt).", es: "Apps nativas Android, HarmonyOS, Windows. Próximamente WireGuard / Clash.", de: "Native Apps Android, HarmonyOS, Windows. WireGuard / Clash kommt.", it: "App native Android, HarmonyOS, Windows. WireGuard / Clash in arrivo.", ja: "Android · HarmonyOS · Windows のネイティブアプリ。今後 WireGuard / Clash 互換。", ko: "Android, HarmonyOS, Windows 네이티브 앱. WireGuard / Clash 호환 예정.", tr: "Android, HarmonyOS ve Windows için yerel uygulamalar. WireGuard / Clash uyumluluğu planlanıyor.", ar: "تطبيقات أصلية لـ Android و HarmonyOS و Windows. توافق WireGuard / Clash مُخطَّط.", ru: "Нативные приложения для Android, HarmonyOS и Windows. WireGuard / Clash — скоро." },
  faq_q4: { en: "Refunds?", zh: "退款政策？", fr: "Remboursements ?", es: "¿Reembolsos?", de: "Rückerstattungen?", it: "Rimborsi?", ja: "返金は？", ko: "환불은요?", tr: "İade?", ar: "استرداد؟", ru: "Возвраты?" },
  faq_a4: { en: "7-day no-questions-asked money-back guarantee on all plans.", zh: "全部套餐 7 天无理由退款保证。", fr: "Remboursement 7 jours sans questions.", es: "Reembolso 7 días sin preguntas.", de: "7 Tage Geld-zurück ohne Fragen.", it: "Rimborso 7 giorni senza domande.", ja: "7 日間無条件返金保証。", ko: "7일 무조건 환불 보장.", tr: "Tüm planlarda 7 gün koşulsuz iade.", ar: "ضمان استرداد لمدة 7 أيام بلا أسئلة.", ru: "Возврат в течение 7 дней без вопросов." },
  faq_q5: { en: "How many devices can I connect?", zh: "可以连接几台设备？", fr: "Combien d'appareils ?", es: "¿Cuántos dispositivos puedo conectar?", de: "Wie viele Geräte?", it: "Quanti dispositivi?", ja: "デバイスは何台？", ko: "기기 몇 개 연결 가능?", tr: "Kaç cihaza bağlanabilirim?", ar: "كم جهازًا يمكنني توصيله؟", ru: "Сколько устройств можно подключить?" },
  faq_a5: { en: "Up to 3 devices simultaneously per account, with free node switching between them.", zh: "每个账户最多同时 3 台设备，节点之间可免费切换。", fr: "Jusqu'à 3 appareils, bascule libre entre eux.", es: "Hasta 3 dispositivos con cambio libre.", de: "Bis zu 3 Geräte mit freiem Wechsel.", it: "Fino a 3 dispositivi con switch libero.", ja: "アカウントごとに同時 3 台、ノード切替自由。", ko: "계정당 동시 3대, 노드 자유 전환.", tr: "Hesap başına 3 cihaza kadar, serbest düğüm geçişi.", ar: "حتى 3 أجهزة لكل حساب مع تبديل حر للنقاط.", ru: "До 3 устройств на аккаунт, со свободным переключением узлов." },
  faq_q6: { en: "Is MirrorSpeed legal?", zh: "MirrorSpeed 合法吗？", fr: "MirrorSpeed est-il légal ?", es: "¿Es legal MirrorSpeed?", de: "Ist MirrorSpeed legal?", it: "MirrorSpeed è legale?", ja: "MirrorSpeed は合法ですか？", ko: "MirrorSpeed는 합법인가요?", tr: "MirrorSpeed yasal mı?", ar: "هل MirrorSpeed قانوني؟", ru: "Легален ли MirrorSpeed?" },
  faq_a6: { en: "MirrorSpeed is a privacy and performance tool. Local laws vary — please ensure compliance with your jurisdiction.", zh: "MirrorSpeed 是隐私与性能工具。各地法律不同，请遵守当地法规。", fr: "Outil de confidentialité et de performance. Vérifiez votre juridiction.", es: "Herramienta de privacidad y rendimiento. Verifica tu jurisdicción.", de: "Datenschutz- und Leistungstool. Bitte lokale Gesetze prüfen.", it: "Strumento di privacy e prestazioni. Verifica le leggi locali.", ja: "プライバシーとパフォーマンスのツールです。各国の法律をご確認ください。", ko: "프라이버시·성능 도구입니다. 관할 법규를 확인하세요.", tr: "Gizlilik ve performans aracıdır. Yerel yasalara uyun.", ar: "أداة خصوصية وأداء. التزم بالقوانين المحلية.", ru: "Инструмент приватности и производительности. Соблюдайте местные законы." },

  // Final CTA
  cta_h1: { en: "Start reflecting", zh: "立即开启", fr: "Commencez à refléter", es: "Empieza a reflejar", de: "Beginne zu spiegeln", it: "Inizia a riflettere", ja: "今すぐミラー開始", ko: "지금 미러링 시작", tr: "Yansıtmaya başla", ar: "ابدأ الانعكاس", ru: "Начни зеркалить" },
  cta_h2: { en: "today.", zh: "镜像之旅。", fr: "aujourd'hui.", es: "hoy.", de: "heute.", it: "oggi.", ja: "今日から。", ko: "오늘부터.", tr: "bugün.", ar: "اليوم.", ru: "сегодня." },
  cta_sub: { en: "Join 100,000+ users who've left tunneling behind. Mirror your traffic at the speed of light. Subscribe and cancel anytime.", zh: "加入超过 10 万用户。把传统隧道抛在脑后，以光速镜像你的流量。可随时取消。", fr: "Rejoignez 100 000+ utilisateurs qui ont laissé le tunneling derrière. Reflétez à la vitesse de la lumière.", es: "Únete a 100 000+ usuarios. Refleja tu tráfico a la velocidad de la luz.", de: "Schließe dich 100.000+ Nutzern an. Spiegele deinen Traffic in Lichtgeschwindigkeit.", it: "Unisciti a 100.000+ utenti. Specchia il traffico alla velocità della luce.", ja: "10 万を超えるユーザーが従来のトンネルを卒業。光速でミラーを。", ko: "10만+ 사용자가 터널링을 떠났습니다. 빛의 속도로 미러링하세요.", tr: "100.000+ kullanıcıya katıl. Trafiğini ışık hızında yansıt.", ar: "انضم لأكثر من 100,000 مستخدم. اعكس حركة بياناتك بسرعة الضوء.", ru: "Присоединяйтесь к 100 000+ пользователей. Зеркальте трафик со скоростью света." },
  cta_btn: { en: "Get Started", zh: "立即开始", fr: "Commencer", es: "Comenzar", de: "Loslegen", it: "Inizia", ja: "始める", ko: "시작하기", tr: "Başla", ar: "ابدأ الآن", ru: "Начать" },
  cta_compare: { en: "Compare plans", zh: "比较方案", fr: "Comparer les plans", es: "Comparar planes", de: "Pläne vergleichen", it: "Confronta piani", ja: "プラン比較", ko: "플랜 비교", tr: "Planları karşılaştır", ar: "قارن الخطط", ru: "Сравнить планы" },
  cta_trust: { en: "7-day money-back · No-logs · Cancel anytime", zh: "7 天退款 · 零日志 · 随时取消", fr: "Remb. 7 jours · Zéro log · Annulez à tout moment", es: "Reembolso 7 días · Sin logs · Cancela cuando quieras", de: "7 Tage Rückgabe · Keine Logs · Jederzeit kündbar", it: "Rimborso 7 giorni · Zero log · Annulla", ja: "7 日返金 · ノーログ · いつでも解約", ko: "7일 환불 · 무로그 · 언제든 해지", tr: "7 gün iade · Sıfır log · İstediğin an iptal", ar: "استرداد 7 أيام · بدون سجلات · إلغاء", ru: "Возврат 7 дней · Без логов · Отмена" },

  // Footer
  ft_tagline: { en: "Mirror-latency VPN powered by the MirrorSpeed in-house engine. Engineered for the speed of light.", zh: "由 MirrorSpeed 自研引擎驱动的镜像延迟 VPN。为光速而生。", fr: "VPN à miroir de latence propulsé par le moteur MirrorSpeed. Conçu pour la vitesse de la lumière.", es: "VPN de espejo de latencia con motor propio. Diseñado para la velocidad de la luz.", de: "Spiegellatenz-VPN mit eigenem MirrorSpeed-Motor.", it: "VPN a specchio di latenza con motore proprietario.", ja: "MirrorSpeed 自社エンジンによるミラーレイテンシ VPN。", ko: "MirrorSpeed 자체 엔진 기반 미러 레이턴시 VPN.", tr: "MirrorSpeed kendi motoruyla ayna-gecikme VPN.", ar: "VPN بانعكاس الكمون مدعوم بمحرك MirrorSpeed الداخلي.", ru: "VPN с зеркальной задержкой на собственном движке MirrorSpeed." },
  ft_product: { en: "Product", zh: "产品", fr: "Produit", es: "Producto", de: "Produkt", it: "Prodotto", ja: "プロダクト", ko: "제품", tr: "Ürün", ar: "المنتج", ru: "Продукт" },
  ft_company: { en: "Company", zh: "公司", fr: "Société", es: "Empresa", de: "Unternehmen", it: "Azienda", ja: "会社", ko: "회사", tr: "Şirket", ar: "الشركة", ru: "Компания" },
  ft_servers: { en: "Servers", zh: "节点", fr: "Serveurs", es: "Servidores", de: "Server", it: "Server", ja: "サーバー", ko: "서버", tr: "Sunucular", ar: "الخوادم", ru: "Серверы" },
  ft_support: { en: "Support", zh: "支持", fr: "Support", es: "Soporte", de: "Support", it: "Supporto", ja: "サポート", ko: "지원", tr: "Destek", ar: "الدعم", ru: "Поддержка" },
  ft_privacy: { en: "Privacy", zh: "隐私", fr: "Confidentialité", es: "Privacidad", de: "Datenschutz", it: "Privacy", ja: "プライバシー", ko: "프라이버시", tr: "Gizlilik", ar: "الخصوصية", ru: "Приватность" },
  ft_ops: { en: "All edges operational", zh: "全部节点正常", fr: "Tous les edges opérationnels", es: "Todos los edges operativos", de: "Alle Edges aktiv", it: "Tutti gli edge operativi", ja: "全エッジ稼働中", ko: "전 엣지 정상", tr: "Tüm edge'ler aktif", ar: "جميع النقاط تعمل", ru: "Все edge активны" },
  ft_rights: { en: "All rights reserved.", zh: "保留所有权利。", fr: "Tous droits réservés.", es: "Todos los derechos reservados.", de: "Alle Rechte vorbehalten.", it: "Tutti i diritti riservati.", ja: "全著作権所有。", ko: "모든 권리 보유.", tr: "Tüm hakları saklıdır.", ar: "جميع الحقوق محفوظة.", ru: "Все права защищены." },
};

export const detectLang = () => {
  // 1. localStorage override
  try {
    const saved = localStorage.getItem("ms_lang");
    if (saved && D.nav_features[saved]) return saved;
  } catch (_) {}

  const supported = SUPPORTED_LANGS.map((l) => l.code);

  // 2. Timezone hint
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (TZ_TO_LANG[tz] && supported.includes(TZ_TO_LANG[tz])) return TZ_TO_LANG[tz];
  } catch (_) {}

  // 3. Navigator language
  const navs = navigator.languages || [navigator.language || "en"];
  for (const n of navs) {
    const short = n.toLowerCase().slice(0, 2);
    if (supported.includes(short)) return short;
  }
  return "en";
};

export const t = (key, lang) => {
  const e = D[key];
  if (!e) return key;
  return e[lang] || e.en || key;
};
