name: amneziawg_flutter
description: AmneziaWG (obfuscated WireGuard) Flutter plugin for Android, iOS and Windows.
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.amneziawg.amneziawg_flutter
        pluginClass: AmneziawgFlutterPlugin
      ios:
        pluginClass: AmneziawgFlutterPlugin
      windows:
        pluginClass: AmneziawgFlutterPluginCApi
        fileName: amneziawg_flutter_plugin_c_api.h

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
